const API_ADDRESS = "https://mainnet-node.tanglebay.com/api/v1/addresses/";
const BOT_TOKEN = "INSERT_YOUR_BOT_TOKEN";
const TREASURY_HOTWALLET = "INSERT_YOUR_TREASURY_HOTWALLET_ADDRESS";
const TREASURY_ADDRESS = "INSERT_YOUR_TREASURY_COLDWALLET_ADDRESS";
const COLLECTION_ID = 'INSERT_THE_ID_OF_THE_NFT_COLLECTION';
const ROLE_ID = "INSERT_THE_ROLE_ID_YOU_WANT_TO_NFT_OWNERS";
const GUILD_ID = "INSERT_YOUR_GUILD_ID";
const GRANT_ROLES_TO_NFT_HOLDERS = true;
const SHOW_TREASURY_INFO = true;

export {API_ADDRESS};
export {BOT_TOKEN};
export {TREASURY_HOTWALLET};
export {TREASURY_ADDRESS};
export {COLLECTION_ID};
export {ROLE_ID};
export {GUILD_ID};
export {GRANT_ROLES_TO_NFT_HOLDERS};
export {SHOW_TREASURY_INFO};